{% set name = "igwn-segments" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/igwn-segments/igwn_segments-{{ version }}.tar.gz
  sha256: 71931772a6af0f581a252cab84c7f2a696a219c71c5e5750682353d651f23229

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [python_impl != 'cpython']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    # extras for cross-compiling:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=70.0.0
    - setuptools-scm >=8
  run:
    - python

test:
  source_files:
    - test/
  requires:
    - pip
    - pytest >=3.9.1
    - python-lal  # [not win and not py>=314]
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show igwn-segments
    # run tests
    - python -m pytest test

about:
  home: https://git.ligo.org/computing/software/igwn-segments/
  dev_url: https://git.ligo.org/computing/software/igwn-segments.git
  doc_url: https://igwn-segments.readthedocs.io/
  summary: Representations of semi-open intervals
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    This module defines the segment and segmentlist objects, as well as the
    infinity object used to define semi-infinite and infinite segments.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
    - titodalcanton
