{% set name = "igwn-segments" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/igwn-segments/igwn_segments-{{ version }}.tar.gz
  sha256: c1ea58c1d7656c99ae1d3a1db260a98f2f846ce7f0b22933050df7f6057492c4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [python_impl != 'cpython']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    # extras for cross-compiling:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python

test:
  source_files:
    - test/
  requires:
    - pip
    - pytest
    - make  # [not win and not py>=313]
    - python-lal  # [not win and not py>=313]
  commands:
    # run_test.py contains sanity checks for all platforms
    # check requirements
    - python -m pip check
    # run tests (only where we can install LAL)
    - make -C test check  # [not win and not py>=313]

about:
  home: https://git.ligo.org/computing/software/igwn-segments/
  dev_url: https://git.ligo.org/computing/software/igwn-segments.git
  doc_url: https://igwn-segments.readthedocs.io/
  summary: Representations of semi-open intervals
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    This module defines the segment and segmentlist objects, as well as the
    infinity object used to define semi-infinite and infinite segments.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
    - titodalcanton
